---
#
# docker-compose -p drupsible -f docker-compose-provision.yml build
#
version: '3'
services:
  varnish:
    hostname: varnish
    build:
      context: .
      dockerfile: Dockerfile
      args:
        limitgroup: mydocker-local_varnish
        playbook: config.yml
        tags: provision
        ansibleversion: '2.3.3.0'
        fromimage: phusion/baseimage
    depends_on:
    - web
  web:
    hostname: web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        limitgroup: mydocker-local_deploy
        playbook: config.yml
        tags: provision
        ansibleversion: '2.3.3.0'
        fromimage: phusion/baseimage
