---
- name: Common configuration (DebOps) for all hosts
  hosts: [ '{{ app_name }}' ]
  gather_facts: True
  become: True
  roles:
  - role: debops.secret
    tags: [ 'role::secret', 'role::pki', 'role::pki:secret' ]
  - role: debops.etc_services
    tags: [ 'role::etc_services' ]
  - role: debops.ferm
    tags: [ 'role::ferm' ]
    ferm_dependent_rules:
    - '{{ sshd__ferm__dependent_rules }}'
  - role: debops.tcpwrappers
    tags: [ 'role::tcpwrappers' ]
    tcpwrappers_dependent_allow:
    - '{{ sshd__tcpwrappers__dependent_allow }}'
  - role: debops.sshkeys
    tags: [ 'role::sshkeys' ]
  - role: debops.sshd
    tags: [ 'role::sshd' ]
- name: MySQL
  hosts: [ '{{ app_name }}-{{ app_target }}_mysql' ]
  become: True
  roles:
  - role: drupsible.mysql
    tags: [ 'role::mysql' ]
    mysql_databases:
    - name: "{{ app_name }}"
      state: 'present'
    - name: "{{ app_name }}_{{ build }}"
      state: "{{ app_db_create_for_build_enabled|default(False)|bool|ternary('present', 'absent') }}"
    mysql_users:
    - name: "{{ app_db_user }}"
      host: "%"
      state: 'present'
      password: '{{ app_db_password | default(lookup("password", secret + "/credentials/" + app_name + "/mysql/" + app_db_user + "/password chars=ascii_letters,digits,hexdigits length=" + mysql_password_length)) }}'
      priv: '{{ app_db_name }}.*:ALL'
    - name: "{{ app_db_user }}"
      host: localhost
      state: 'present'
      password: '{{ app_db_password | default(lookup("password", secret + "/credentials/" + app_name + "/mysql/" + app_db_user + "/password chars=ascii_letters,digits,hexdigits length=" + mysql_password_length)) }}'
      priv: '{{ app_db_name }}.*:ALL'
    - name: "{{ app_db_user }}"
      host: "{{ ansible_hostname }}"
      state: 'present'
      password: '{{ app_db_password | default(lookup("password", secret + "/credentials/" + app_name + "/mysql/" + app_db_user + "/password chars=ascii_letters,digits,hexdigits length=" + mysql_password_length)) }}'
      priv: '{{ app_db_name }}.*:ALL'
    - name: "{{ app_db_user }}"
      host: "10.0.2.2"
      state: 'present'
      password: '{{ app_db_password | default(lookup("password", secret + "/credentials/" + app_name + "/mysql/" + app_db_user + "/password chars=ascii_letters,digits,hexdigits length=" + mysql_password_length)) }}'
      priv: '{{ app_db_name }}.*:ALL'
- name: Ferm/Postfix/PHP/Composer/New Relic/Apache/uploadprogress
  hosts: [ '{{ app_name }}-{{ app_target }}_deploy' ]
  become: True
  roles:
  - role: debops.pki/env
    tags: [ 'role::pki', 'role::secret' ]
    when: app_https_enabled|default(False)|bool or 
      (smtp_server is defined and 
      smtp_port is defined and 
      smtp_user is defined)
  - role: debops.secret
    tags: [ 'role::secret', 'role::pki', 'role::pki:secret' ]
    secret_directories:
    - "{{ pki_env_secret_directories|default('') }}"
    when: app_https_enabled|default(False)|bool or 
      (smtp_server is defined and 
      smtp_port is defined and 
      smtp_user is defined)
  - role: debops.dhparam
    tags: [ 'role::dhparam' ]
    when: app_https_enabled|default(False)|bool or 
      (smtp_server is defined and 
      smtp_port is defined and 
      smtp_user is defined)
  - role: debops.pki
    tags: [ 'role::pki' ]
    when: app_https_enabled|default(False)|bool or 
      (smtp_server is defined and 
      smtp_port is defined and 
      smtp_user is defined)
  - role: debops.ferm
    tags: [ 'role::ferm:deploy' ]
    ferm_dependent_rules:
    - '{{ postfix_ferm_dependent_rules|default([]) }}'
    - '{{ apache2_ferm_dependent_rules }}'
    - '{{ samba_ferm_dependent_rules|default([]) }}'
  - role: debops.postfix
    tags: [ 'role::postfix' ]
    postfix: [ 'client' ]
    postfix_relayhost: "[{{ smtp_server }}]:{{ smtp_port }}"
    postfix_smtp_sasl_password_map: "{ '[{{ smtp_server }}]:{{ smtp_port }}': '{{ smtp_user }}' }"
    when: smtp_server is defined and smtp_port is defined and smtp_user is defined
  - role: debops.users
    users_enabled: True
    users_list:
    - name: "{{ app_user }}"
      forward: "{{ app_admin_email }}"
      shell: '/bin/bash'
      state: 'present'
    users_admins: [ "{{ app_user }}" ]
    tags: [ 'role::users' ]
  - role: debops.php5
    tags: [ 'role::php5' ]
    when: apache2_mpm != 'prefork'
  - role: drupsible.newrelic
    tags: [ 'role::newrelic' ]
    when: provision_new_relic|default(False)|bool and 'newrelic-php5' in apache2_php5_packages_ontop and apache2_mpm == 'prefork'
  - role: drupsible.apache2
    tags: [ 'role::apache2' ]
    apache2_pki_crt: "{{ deploy_pki_crt|default('/etc/pki/realms/domain/default.crt') }}"
    apache2_pki_key: "{{ deploy_pki_key|default('/etc/pki/realms/domain/default.key') }}"
    apache2_port: "{{ (app_varnish_enabled|default(False)|bool)|ternary(80, app_apache2_alt_port) }}"
    apache2_https_enabled: "{{ app_https_enabled }}"
    apache2_fpm_server_status_path: "{{ app_fpm_status_path | default('/fpm-status') }}"
    apache2_fpm_ping_path: "{{ app_fpm_ping_path | default('/ping') }}"
    apache2_webhost: "{{ app_webhost }}"
    apache2_fpm_listen: "{{ app_fpm_listen }}"
    apache2_fpm_listen_uds: "{{ app_fpm_listen_uds }}"
  - role: drupsible.uploadprogress
    tags: [ 'role::uploadprogress' ]
  - role: drupsible.xdebug
    tags: [ 'role::xdebug' ]
    xdebug_cli_enabled: "{{ app_xdebug_cli_enabled|default(False) }}"
    when: app_target|default('local') in app_xdebug_targets|default([ 'local', 'ci', 'qa' ])
  - role: drupsible.composer
    tags: [ 'role::composer' ]
  - role: drupsible.memcached
    when: app_memcached_enabled|default(True)|bool
    tags: [ 'role::memcached' ]
  - role: drupsible.newrelic
    when: provision_new_relic|default(False)|bool
    tags: [ 'role::newrelic' ]
  - role: drupsible.drush
    drush_min_version: "{{ app_drush_min_version|default('8.0.5') }}"
    tags: [ 'role::drush' ]
  - role: drupsible.samba
    samba_webhost: "{{ app_webhost }}"
    when: app_target == 'local'
    tags: [ 'role::samba' ]
- name: Varnish
  hosts: [ '{{ app_name }}-{{ app_target }}_varnish' ]
  become: True
  roles:
  - role: debops.secret
    tags: [ 'role::secret', 'role::varnish:secret' ]
  - role: debops.ferm
    tags: [ 'role::ferm:varnish' ]
    ferm_dependent_rules:
    - '{{ varnish_ferm_dependent_rules }}'
  - role: drupsible.varnish
    tags: [ 'role::varnish' ]
    trusted_hosts: "{{ app_server_aliases }}"
    varnish_pipe_timeout: 600
    varnish_apache2_port: "{{ app_apache2_alt_port|default('8080') }}"
    varnish_management_console_listen_on: "{{ app_varnish_mgmt_port|default('6082') }}"
    varnish_fpm_ping_path: "{{ app_fpm_ping_path | default('/ping') }}"
    varnish_webhost: "{{ app_webhost }}"
    varnish_app_name: "{{ app_name }}"
    when: app_varnish_enabled|bool
