---
- name: Deploy
  hosts: [ '{{ app_name }}-{{ app_target }}_deploy' ]
  gather_facts: True

  pre_tasks:
  - name: Gather facts of Varnish servers
    setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    with_items: "{{ groups[app_name + '-' + app_target + '_varnish'] }}"

  - name: Lookup control key secret and set the fact to avoid lookups lazy evaluation
    set_fact:
      deploy_varnish_control_key__: "{{ lookup('password', secret + '/credentials/' + inventory_hostname + '/varnish/secret chars=ascii_letters,digits,hexdigits') }}"
    no_log: True

  roles:
  - role: debops.secret
    tags: [ secret, deploy, secret-deploy ]
  - role: drupsible.deploy
    tags: [ deploy, deploy-deploy ]
    deploy_build_id: "{{ app_build_id }}"
    deploy_varnish_enabled: "{{ app_varnish_enabled }}"
    deploy_varnish_mgmt_port: "{{ app_varnish_mgmt_port|default('6082') }}"
    deploy_target: "{{ app_target }}"
    deploy_webhost: "{{ app_webhost }}"
    deploy_trusted_host_patterns: [ "(?i)^.+\\.{{ app_webdomain|regex_replace('[.]', '\\.') }}$" ]
    deploy_varnish_servers: "{{ groups[ app_name + '-' + app_target + '_varnish' ] }}"
    deploy_mysql_host: "{{ groups[ app_name + '-' + app_target + '_mysql' ][0] }}"
    deploy_db_name: "{{ app_db_name }}"
    deploy_db_user: "{{ app_db_user }}"
    deploy_db_password: '{{ app_db_password|default(lookup("password", secret + "/credentials/" + app_name + "/mysql/" + app_db_user + "/password chars=ascii_letters,digits,hexdigits")) }}'
