---
- name: Deploy
  hosts: drupsible_deploy

  pre_tasks:
  - name: Put PHP5 packages in a parameter for calling debops.php5
    set_fact:
      deploy_php5_packages: "{{ php5_packages}}"

  - name: Add New Relic PHP5 pkg if needed
    set_fact:
      deploy_php5_packages: "{{ [ 'newrelic-php5' ] + php5_packages}}"
    when: provision_new_relic|default(False)|bool

  roles:
  - role: debops.users
    sudo: yes
    users: True
    users_list:
    - name: "{{ app_env['user'] }}"
      forward: "{{ app_env['admin_email'] }}"
      state: 'present'
    users_admins: [ "{{ app_env['user'] }}" ]
    tags: config.users
    
  - role: drupsible.drush
    tags: drush
  
  - role: drupsible.newrelic
    when: provision_new_relic|default(False)|bool
    sudo: yes
    tags: newrelic

  - role: debops.php5
    when: apache2_mpm != 'prefork'
    sudo: yes
    php5_packages: "{{ deploy_php5_packages }}"
    php5_app_pool:
      enabled: True
      name: "{{ app_name }}"
      listen: "{{ app_env['fpm_listen'] }}"
      user: "{{ app_env['user'] }}"
      group: "{{ app_env['group'] }}"
      php_flag: "{{ php_flag }}"
      php_value: "{{ php_value }}"
    php5_pools: [ '{{ php5_app_pool }}' ]
    tags: config.php5

  - role: drupsible.memcached
    when: app_env.memcached|bool
    sudo: yes
    tags: memcached

  - role: drupsible.samba
    samba_webhost: "{{ deploy_webhost }}"
    when: deploy_target is defined and deploy_target == 'local'
    sudo: yes
    tags: samba

  - role: drupsible.deploy
    tags: deploy
    deploy_varnish_enabled: "{{ app_env['varnish_enabled'] }}"
    deploy_varnish_mgmt_port: "{{ app_env['varnish_mgmt_port'] }}"
    deploy_target: "{{ app_target }}"
    deploy_webhost: "{{ app_webhost }}"
    trusted_host_patterns: [ "(?i)^.+\\.{{ webdomain|regex_replace('[.]', '\\.') }}$" ]
