---
- name: Deploy
  hosts: drupsible_deploy

  roles:
  - role: debops.users
    become: yes
    users_enabled: True
    users_list:
    - name: "{{ app_env['user'] }}"
      forward: "{{ app_env['admin_email'] }}"
      state: 'present'
    users_admins: [ "{{ app_env['user'] }}" ]
    tags: config.users

  - role: debops.php5
    when: apache2_mpm != 'prefork'
    become: yes
    php5_packages: "{{ provision_new_relic|default(False)|bool|ternary([ 'newrelic-php5' ], [] ) }}"
    php5_app_pool:
      enabled: True
      name: "{{ app_name }}"
      listen: "{{ app_env['fpm_listen'] }}"
      user: "{{ app_env['user'] }}"
      group: "{{ app_env['group'] }}"
      php_flag: "{{ php_flag }}"
      php_value: "{{ php_value }}"
    php5_pools: [ '{{ php5_app_pool }}' ]
    tags: config.php5

  - role: drupsible.xdebug
    become: yes
    tags: [ 'role::xdebug' ]
    when: "app_target in deploy_xdebug_targets"

  - role: drupsible.composer
    become: yes
    tags: composer

  - role: drupsible.drush
    tags: drush

  - role: drupsible.newrelic
    when: provision_new_relic|default(False)|bool
    become: yes
    tags: newrelic

  - role: drupsible.memcached
    when: app_env.memcached|bool
    become: yes
    tags: memcached

  - role: drupsible.samba
    samba_webhost: "{{ deploy_webhost }}"
    when: deploy_target is defined and deploy_target == 'local'
    become: yes
    tags: samba

  - role: drupsible.deploy
    tags: deploy
    deploy_varnish_enabled: "{{ app_env['varnish_enabled'] }}"
    deploy_varnish_mgmt_port: "{{ app_env['varnish_mgmt_port'] }}"
    deploy_target: "{{ app_target }}"
    deploy_webhost: "{{ app_webhost }}"
    trusted_host_patterns: [ "(?i)^.+\\.{{ webdomain|regex_replace('[.]', '\\.') }}$" ]
