---
- name: Deploy
  hosts: [ '{{ app_name }}-{{ app_target }}_deploy' ]
  roles:
  - role: debops.secret
    tags: [ 'role::secret', 'role::deploy:secret' ]
  - role: debops.php5
    when: apache2_mpm != 'prefork'
    become: yes
    php5_app_pool:
      enabled: True
      name: "{{ app_name }}"
      listen: "{{ ansible_local.apache2.uds_available|default(True)|bool|ternary(app_fpm_listen_uds, app_fpm_listen) }}"
      user: "{{ app_user }}"
      group: "{{ app_group }}"
      php_flag: "{{ php_flag }}"
      php_value: "{{ php_value }}"
    php5_pools: [ '{{ php5_app_pool }}' ]
    tags: config.php5
  - role: drupsible.deploy
    tags: deploy
    build: "{{ app_build_id }}"
    deploy_varnish_enabled: "{{ app_varnish_enabled }}"
    deploy_varnish_mgmt_port: "{{ app_varnish_mgmt_port|default('6082') }}"
    deploy_target: "{{ app_target }}"
    deploy_webhost: "{{ app_webhost }}"
    trusted_host_patterns: [ "(?i)^.+\\.{{ webdomain|regex_replace('[.]', '\\.') }}$" ]
    deploy_mysql_host: "{{ groups[ app_name + '-' + app_target + '_mysql' ][0] }}"
    deploy_db_name: "{{ app_db_name }}"
    deploy_db_user: "{{ app_db_user }}"
    deploy_db_password: '{{ app_db_password|default(lookup("password", secret + "/credentials/" + app_name + "/mysql/" + app_db_user + "/password chars=ascii_letters,digits,hexdigits")) }}'
