---
- name: Deploy
  hosts: drupsible_deploy

  roles:
  - role: debops.php5
    when: apache2_mpm != 'prefork'
    become: yes
    php5_app_pool:
      enabled: True
      name: "{{ app_name }}"
      listen: "{{ app_env['fpm_listen'] }}"
      user: "{{ app_env['user'] }}"
      group: "{{ app_env['group'] }}"
      php_flag: "{{ php_flag }}"
      php_value: "{{ php_value }}"
    php5_pools: [ '{{ php5_app_pool }}' ]
    tags: config.php5

  - role: drupsible.deploy
    tags: deploy
    deploy_varnish_enabled: "{{ app_env['varnish_enabled'] }}"
    deploy_varnish_mgmt_port: "{{ app_env['varnish_mgmt_port'] }}"
    deploy_target: "{{ app_target }}"
    deploy_webhost: "{{ app_webhost }}"
    trusted_host_patterns: [ "(?i)^.+\\.{{ webdomain|regex_replace('[.]', '\\.') }}$" ]
