---
app_target: prod
app_webhost: www

app_env:
  aliases:
    - "{{ webdomain }}"
  user: example-project
  group: www-data
  fpm_listen: '/var/run/php5-fpm-{{ app_name }}.sock'
  admin_email: "admin@{{ webdomain }}"
  files_tarball_filename: '{{ app_name }}-files.tar.gz'
  db_dump_filename: '{{ app_name }}.sql.gz'
  db_name: "{{ app_name }}"
  db_user: "{{ app_name }}"
  # Set to True if the target env has memcached available
  memcached: True
  # True clones the cur database
  db_clone: False
  # True looks for a DB dump to upload and import
  db_import: False
  # True syncs with source DB
  db_sync: False
  # True looks for tarballs (files) to upload and import
  files_import: False
  files_sync: False
  files_copy: True
  do_cur_backup: True
  adjust_db: True
  syslog: yes
  https_enabled: no
  varnish_enabled: yes
  varnish_mgmt_port: 6082
  app_apache2_alt_port: 8080

codebase_tarball_filename: '{{ app_name }}-codebase.tar.gz'
codebase_import: no

git_repo_protocol: ''
git_repo_server: ''
git_repo_user: ''
git_repo_path: ''
git_repo_pass: ''
git_version: ''

deploy_site_install: no
deploy_install_profile: ''

deploy_drupal_fast_404: no
deploy_proxy_server: ''
deploy_proxy_port: 8080
deploy_proxy_username: ''
deploy_proxy_password: ''
deploy_proxy_user_agent: ''
deploy_proxy_exceptions: 
  - '127.0.0.1'
  - 'localhost'
deploy_container_base_class: '\Drupal\Core\DependencyInjection\Container'

config_dirs: []
deploy_identifier: '\Drupal::VERSION'
drush_min_version: 7.*

deploy_pki_crt: '/etc/pki/realms/domain/default.crt'
deploy_pki_key: '/etc/pki/realms/domain/default.key'
