---
#
# Configuration file for the deploy/webserver group of the LOCAL environment.
#

# Reset admin password in local
deploy_reset_admin_pass: yes

# Always devel enabled
deploy_modules_present_env: [ 'devel' ]
# Always cdn disabled
deploy_modules_absent_env: [ 'cdn' ]
# Xdebug extension enabled
deploy_xdebug_enabled: yes

# PHP development settings, YAY!
php5_max_execution_time: '0'
php5_max_input_time: '-1'

# SQLite added in local for Drupal Console
php__packages:
# Add xml in Xenial if you need PECL (like when downgrading to PHP 5.6)
#- xml
- php-pear
- php-soap
- gmp
- mysql
- sqlite

# No New Relic in local
apache2_mod_php5_packages_ontop:
- php-pear
- php-soap
- php5-curl
- php5-gd
- php5-gmp
- php5-mcrypt
- php5-memcache
- php5-mysql
- imagemagick

# Also allow Vagrant-host
apache2_allowed_hosts: [ "127.0.0.1", "10.0.2.2" ]

# Default to NOT update translations in local
deploy_update_translations_enabled: False
